ALTER TABLE threads ADD COLUMN worktree TEXT NOT NULL DEFAULT '';
ALTER TABLE threads ADD COLUMN worktree_branch TEXT NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN worktrees INTEGER NOT NULL DEFAULT 0;
